apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-api
  namespace: app-signals-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sample-api
  template:
    metadata:
      labels:
        app: sample-api
    spec:
      containers:
        - name: sample-api
          image: public.ecr.aws/docker/library/nginx:stable
          ports:
            - containerPort: 80
